import "bulma/css/bulma.min.css"
import "./globals.css"
import { Footer, Navbar } from "@/components/other-components"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
